#!/bin/bash

# Make sure you have yq installed: https://github.com/mikefarah/yq

YAML_FILE="config.yaml"
APPLIST="APPLIST.md"

# Create the APPLIST.md file and write the table header
echo "| App Name | Version | Changelog |" > ${APPLIST}
echo "| :------: | :-----: | :------- |" >> ${APPLIST}

# Get the list of app names
app_names=$(yq e '.apps | keys | .[]' "$YAML_FILE")

# Loop through each app and extract the required information
for app_name in $app_names; do
  version=$(yq e ".apps.$app_name.replacements | match(\"VERSION=([a-z0-9.]+)\").captures[0].string" "$YAML_FILE")
  changelog=$(yq e ".apps.$app_name.changelog" "$YAML_FILE")

  # Add the app information to the ${APPLIST} file
  echo "| $app_name | $version | $changelog |" >> ${APPLIST}
done

# Transcrypt pre-commit hook: fail if secret file in staging lacks the magic prefix "Salted" in B64
RELATIVE_GIT_DIR=$(git rev-parse --git-dir 2>/dev/null || printf '')
CRYPT_DIR=$(git config transcrypt.crypt-dir 2>/dev/null || printf '%s/crypt' "${RELATIVE_GIT_DIR}")
"${CRYPT_DIR}/transcrypt" pre_commit
